<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoliceStationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('police_stations')->insert([

            ['district_id' => '1','police_station_name' => 'Debidwar','bn_police_station_name' => 'দেবিদ্বার'],
            ['district_id' => '1','police_station_name' => 'Barura','bn_police_station_name' => 'বরুড়া'],
            ['district_id' => '1','police_station_name' => 'Brahmanpara','bn_police_station_name' => 'ব্রাহ্মণপাড়া'],
            ['district_id' => '1','police_station_name' => 'Chandina','bn_police_station_name' => 'চান্দিনা'],
            ['district_id' => '1','police_station_name' => 'Chauddagram','bn_police_station_name' => 'চৌদ্দগ্রাম'],
            ['district_id' => '1','police_station_name' => 'Daudkandi','bn_police_station_name' => 'দাউদকান্দি'],
            ['district_id' => '1','police_station_name' => 'Homna','bn_police_station_name' => 'হোমনা'],
            ['district_id' => '1','police_station_name' => 'Laksam','bn_police_station_name' => 'লাকসাম'],
            ['district_id' => '1','police_station_name' => 'Muradnagar','bn_police_station_name' => 'মুরাদনগর'],
            ['district_id' => '1','police_station_name' => 'Nangalkot','bn_police_station_name' => 'নাঙ্গলকোট'],
            ['district_id' => '1','police_station_name' => 'Comilla Sadar','bn_police_station_name' => 'কুমিল্লা সদর'],
            ['district_id' => '1','police_station_name' => 'Meghna','bn_police_station_name' => 'মেঘনা'],
            ['district_id' => '1','police_station_name' => 'Monohargonj','bn_police_station_name' => 'মনোহরগঞ্জ'],
            ['district_id' => '1','police_station_name' => 'Sadarsouth','bn_police_station_name' => 'সদর দক্ষিণ'],
            ['district_id' => '1','police_station_name' => 'Titas','bn_police_station_name' => 'তিতাস'],
            ['district_id' => '1','police_station_name' => 'Burichang','bn_police_station_name' => 'বুড়িচং'],
            ['district_id' => '1','police_station_name' => 'Lalmai','bn_police_station_name' => 'লালমাই'],
            ['district_id' => '2','police_station_name' => 'Chhagalnaiya','bn_police_station_name' => 'ছাগলনাইয়া'],
            ['district_id' => '2','police_station_name' => 'Feni Sadar','bn_police_station_name' => 'ফেনী সদর'],
            ['district_id' => '2','police_station_name' => 'Sonagazi','bn_police_station_name' => 'সোনাগাজী'],
            ['district_id' => '2','police_station_name' => 'Fulgazi','bn_police_station_name' => 'ফুলগাজী'],
            ['district_id' => '2','police_station_name' => 'Parshuram','bn_police_station_name' => 'পরশুরাম'],
            ['district_id' => '2','police_station_name' => 'Daganbhuiyan','bn_police_station_name' => 'দাগনভূঞা'],
            ['district_id' => '3','police_station_name' => 'Brahmanbaria Sadar','bn_police_station_name' => 'ব্রাহ্মণবাড়িয়া সদর'],
            ['district_id' => '3','police_station_name' => 'Kasba','bn_police_station_name' => 'কসবা'],
            ['district_id' => '3','police_station_name' => 'Nasirnagar','bn_police_station_name' => 'নাসিরনগর'],
            ['district_id' => '3','police_station_name' => 'Sarail','bn_police_station_name' => 'সরাইল'],
            ['district_id' => '3','police_station_name' => 'Ashuganj','bn_police_station_name' => 'আশুগঞ্জ'],
            ['district_id' => '3','police_station_name' => 'Akhaura','bn_police_station_name' => 'আখাউড়া'],
            ['district_id' => '3','police_station_name' => 'Nabinagar','bn_police_station_name' => 'নবীনগর'],
            ['district_id' => '3','police_station_name' => 'Bancharampur','bn_police_station_name' => 'বাঞ্ছারামপুর'],
            ['district_id' => '3','police_station_name' => 'Bijoynagar','bn_police_station_name' => 'বিজয়নগর'],
            ['district_id' => '4','police_station_name' => 'Rangamati Sadar','bn_police_station_name' => 'রাঙ্গামাটি সদর'],
            ['district_id' => '4','police_station_name' => 'Kaptai','bn_police_station_name' => 'কাপ্তাই'],
            ['district_id' => '4','police_station_name' => 'Kawkhali','bn_police_station_name' => 'কাউখালী'],
            ['district_id' => '4','police_station_name' => 'Baghaichari','bn_police_station_name' => 'বাঘাইছড়ি'],
            ['district_id' => '4','police_station_name' => 'Barkal','bn_police_station_name' => 'বরকল'],
            ['district_id' => '4','police_station_name' => 'Langadu','bn_police_station_name' => 'লংগদু'],
            ['district_id' => '4','police_station_name' => 'Rajasthali','bn_police_station_name' => 'রাজস্থলী'],
            ['district_id' => '4','police_station_name' => 'Belaichari','bn_police_station_name' => 'বিলাইছড়ি'],
            ['district_id' => '4','police_station_name' => 'Juraichari','bn_police_station_name' => 'জুরাছড়ি'],
            ['district_id' => '4','police_station_name' => 'Naniarchar','bn_police_station_name' => 'নানিয়ারচর'],
            ['district_id' => '5','police_station_name' => 'Noakhali Sadar','bn_police_station_name' => 'নোয়াখালী সদর'],
            ['district_id' => '5','police_station_name' => 'Companiganj','bn_police_station_name' => 'কোম্পানীগঞ্জ'],
            ['district_id' => '5','police_station_name' => 'Begumganj','bn_police_station_name' => 'বেগমগঞ্জ'],
            ['district_id' => '5','police_station_name' => 'Hatia','bn_police_station_name' => 'হাতিয়া'],
            ['district_id' => '5','police_station_name' => 'Subarnachar','bn_police_station_name' => 'সুবর্ণচর'],
            ['district_id' => '5','police_station_name' => 'Kabirhat','bn_police_station_name' => 'কবিরহাট'],
            ['district_id' => '5','police_station_name' => 'Senbug','bn_police_station_name' => 'সেনবাগ'],
            ['district_id' => '5','police_station_name' => 'Chatkhil','bn_police_station_name' => 'চাটখিল'],
            ['district_id' => '5','police_station_name' => 'Sonaimori','bn_police_station_name' => 'সোনাইমুড়ী'],
            ['district_id' => '6','police_station_name' => 'Haimchar','bn_police_station_name' => 'হাইমচর'],
            ['district_id' => '6','police_station_name' => 'Kachua','bn_police_station_name' => 'কচুয়া'],
            ['district_id' => '6','police_station_name' => 'Shahrasti','bn_police_station_name' => 'শাহরাস্তি	'],
            ['district_id' => '6','police_station_name' => 'Chandpur Sadar','bn_police_station_name' => 'চাঁদপুর সদর'],
            ['district_id' => '6','police_station_name' => 'Matlab South','bn_police_station_name' => 'মতলব দক্ষিণ'],
            ['district_id' => '6','police_station_name' => 'Hajiganj','bn_police_station_name' => 'হাজীগঞ্জ'],
            ['district_id' => '6','police_station_name' => 'Matlab North','bn_police_station_name' => 'মতলব উত্তর'],
            ['district_id' => '6','police_station_name' => 'Faridgonj','bn_police_station_name' => 'ফরিদগঞ্জ'],
            ['district_id' => '7','police_station_name' => 'Lakshmipur Sadar','bn_police_station_name' => 'লক্ষ্মীপুর সদর'],
            ['district_id' => '7','police_station_name' => 'Kamalnagar','bn_police_station_name' => 'কমলনগর'],
            ['district_id' => '7','police_station_name' => 'Raipur','bn_police_station_name' => 'রায়পুর'],
            ['district_id' => '7','police_station_name' => 'Ramgati','bn_police_station_name' => 'রামগতি'],
            ['district_id' => '7','police_station_name' => 'Ramganj','bn_police_station_name' => 'রামগঞ্জ'],
            ['district_id' => '8','police_station_name' => 'Rangunia','bn_police_station_name' => 'রাঙ্গুনিয়া'],
            ['district_id' => '8','police_station_name' => 'Sitakunda','bn_police_station_name' => 'সীতাকুন্ড'],
            ['district_id' => '8','police_station_name' => 'Mirsharai','bn_police_station_name' => 'মীরসরাই'],
            ['district_id' => '8','police_station_name' => 'Patiya','bn_police_station_name' => 'পটিয়া'],
            ['district_id' => '8','police_station_name' => 'Sandwip','bn_police_station_name' => 'সন্দ্বীপ'],
            ['district_id' => '8','police_station_name' => 'Banshkhali','bn_police_station_name' => 'বাঁশখালী'],
            ['district_id' => '8','police_station_name' => 'Boalkhali','bn_police_station_name' => 'বোয়ালখালী'],
            ['district_id' => '8','police_station_name' => 'Anwara','bn_police_station_name' => 'আনোয়ারা'],
            ['district_id' => '8','police_station_name' => 'Chandanaish','bn_police_station_name' => 'চন্দনাইশ'],
            ['district_id' => '8','police_station_name' => 'Satkania','bn_police_station_name' => 'সাতকানিয়া'],
            ['district_id' => '8','police_station_name' => 'Lohagara','bn_police_station_name' => 'লোহাগাড়া'],
            ['district_id' => '8','police_station_name' => 'Hathazari','bn_police_station_name' => 'হাটহাজারী'],
            ['district_id' => '8','police_station_name' => 'Fatikchhari','bn_police_station_name' => 'ফটিকছড়ি'],
            ['district_id' => '8','police_station_name' => 'Raozan','bn_police_station_name' => 'রাউজান'],
            ['district_id' => '8','police_station_name' => 'Karnafuli','bn_police_station_name' => 'কর্ণফুলী'],
            ['district_id' => '9','police_station_name' => 'Coxsbazar Sadar','bn_police_station_name' => 'কক্সবাজার সদর'],
            ['district_id' => '9','police_station_name' => 'Chakaria','bn_police_station_name' => 'চকরিয়া'],
            ['district_id' => '9','police_station_name' => 'Kutubdia','bn_police_station_name' => 'কুতুবদিয়া'],
            ['district_id' => '9','police_station_name' => 'Ukhiya','bn_police_station_name' => 'উখিয়া'],
            ['district_id' => '9','police_station_name' => 'Moheshkhali','bn_police_station_name' => 'মহেশখালী'],
            ['district_id' => '9','police_station_name' => 'Pekua','bn_police_station_name' => 'পেকুয়া'],
            ['district_id' => '9','police_station_name' => 'Ramu','bn_police_station_name' => 'রামু'],
            ['district_id' => '9','police_station_name' => 'Teknaf','bn_police_station_name' => 'টেকনাফ'],
            ['district_id' => '10','police_station_name' => 'Khagrachhari Sadar','bn_police_station_name' => 'খাগড়াছড়ি সদর'],
            ['district_id' => '10','police_station_name' => 'Dighinala','bn_police_station_name' => 'দিঘীনালা'],
            ['district_id' => '10','police_station_name' => 'Panchari','bn_police_station_name' => 'পানছড়ি'],
            ['district_id' => '10','police_station_name' => 'Laxmichhari','bn_police_station_name' => 'লক্ষীছড়ি'],
            ['district_id' => '10','police_station_name' => 'Mohalchari','bn_police_station_name' => 'মহালছড়ি'],
            ['district_id' => '10','police_station_name' => 'Manikchari','bn_police_station_name' => 'মানিকছড়ি'],
            ['district_id' => '10','police_station_name' => 'Ramgarh','bn_police_station_name' => 'রামগড়'],
            ['district_id' => '10','police_station_name' => 'Matiranga','bn_police_station_name' => 'মাটিরাঙ্গা'],
            ['district_id' => '10','police_station_name' => 'Guimara','bn_police_station_name' => 'গুইমারা'],
            ['district_id' => '11','police_station_name' => 'Bandarban Sadar','bn_police_station_name' => 'বান্দরবান সদর'],
            ['district_id' => '11','police_station_name' => 'Alikadam','bn_police_station_name' => 'আলীকদম'],
            ['district_id' => '11','police_station_name' => 'Naikhongchhari','bn_police_station_name' => 'নাইক্ষ্যংছড়ি'],
            ['district_id' => '11','police_station_name' => 'Rowangchhari','bn_police_station_name' => 'রোয়াংছড়ি'],
            ['district_id' => '11','police_station_name' => 'Lama','bn_police_station_name' => 'লামা'],
            ['district_id' => '11','police_station_name' => 'Ruma','bn_police_station_name' => 'রুমা'],
            ['district_id' => '11','police_station_name' => 'Thanchi','bn_police_station_name' => 'থানচি'],
            ['district_id' => '12','police_station_name' => 'Belkuchi','bn_police_station_name' => 'বেলকুচি'],
            ['district_id' => '12','police_station_name' => 'Chauhali','bn_police_station_name' => 'চৌহালি'],
            ['district_id' => '12','police_station_name' => 'Kamarkhand','bn_police_station_name' => 'কামারখন্দ'],
            ['district_id' => '12','police_station_name' => 'Kazipur','bn_police_station_name' => 'কাজীপুর'],
            ['district_id' => '12','police_station_name' => 'Raigonj','bn_police_station_name' => 'রায়গঞ্জ'],
            ['district_id' => '12','police_station_name' => 'Shahjadpur','bn_police_station_name' => 'শাহজাদপুর'],
            ['district_id' => '12','police_station_name' => 'Sirajganj Sadar','bn_police_station_name' => 'সিরাজগঞ্জ সদর'],
            ['district_id' => '12','police_station_name' => 'Tarash','bn_police_station_name' => 'তাড়াশ'],
            ['district_id' => '12','police_station_name' => 'Ullapara','bn_police_station_name' => 'উল্লাপাড়া'],
            ['district_id' => '13','police_station_name' => 'Sujanagar','bn_police_station_name' => 'সুজানগর'],
            ['district_id' => '13','police_station_name' => 'Ishurdi','bn_police_station_name' => 'ঈশ্বরদী'],
            ['district_id' => '13','police_station_name' => 'Bhangura','bn_police_station_name' => 'ভাঙ্গুড়া'],
            ['district_id' => '13','police_station_name' => 'Pabna Sadar','bn_police_station_name' => 'পাবনা সদর'],
            ['district_id' => '13','police_station_name' => 'Bera','bn_police_station_name' => 'বেড়া'],
            ['district_id' => '13','police_station_name' => 'Atghoria','bn_police_station_name' => 'আটঘরিয়া'],
            ['district_id' => '13','police_station_name' => 'Chatmohar','bn_police_station_name' => 'চাটমোহর'],
            ['district_id' => '13','police_station_name' => 'Santhia','bn_police_station_name' => 'সাঁথিয়া'],
            ['district_id' => '13','police_station_name' => 'Faridpur','bn_police_station_name' => 'ফরিদপুর'],
            ['district_id' => '14','police_station_name' => 'Kahaloo','bn_police_station_name' => 'কাহালু'],
            ['district_id' => '14','police_station_name' => 'Bogra Sadar','bn_police_station_name' => 'বগুড়া সদর'],
            ['district_id' => '14','police_station_name' => 'Shariakandi','bn_police_station_name' => 'সারিয়াকান্দি'],
            ['district_id' => '14','police_station_name' => 'Shajahanpur','bn_police_station_name' => 'শাজাহানপুর'],
            ['district_id' => '14','police_station_name' => 'Dupchanchia','bn_police_station_name' => 'দুপচাচিঁয়া'],
            ['district_id' => '14','police_station_name' => 'Adamdighi','bn_police_station_name' => 'আদমদিঘি'],
            ['district_id' => '14','police_station_name' => 'Nondigram','bn_police_station_name' => 'নন্দিগ্রাম'],
            ['district_id' => '14','police_station_name' => 'Sonatala','bn_police_station_name' => 'সোনাতলা'],
            ['district_id' => '14','police_station_name' => 'Dhunot','bn_police_station_name' => 'ধুনট'],
            ['district_id' => '14','police_station_name' => 'Gabtali','bn_police_station_name' => 'গাবতলী'],
            ['district_id' => '14','police_station_name' => 'Sherpur','bn_police_station_name' => 'শেরপুর'],
            ['district_id' => '14','police_station_name' => 'Shibganj','bn_police_station_name' => 'শিবগঞ্জ'],
            ['district_id' => '15','police_station_name' => 'Paba','bn_police_station_name' => 'পবা'],
            ['district_id' => '15','police_station_name' => 'Durgapur','bn_police_station_name' => 'দুর্গাপুর'],
            ['district_id' => '15','police_station_name' => 'Mohonpur','bn_police_station_name' => 'মোহনপুর'],
            ['district_id' => '15','police_station_name' => 'Charghat','bn_police_station_name' => 'চারঘাট'],
            ['district_id' => '15','police_station_name' => 'Puthia','bn_police_station_name' => 'পুঠিয়া'],
            ['district_id' => '15','police_station_name' => 'Bagha','bn_police_station_name' => 'বাঘা'],
            ['district_id' => '15','police_station_name' => 'Godagari','bn_police_station_name' => 'গোদাগাড়ী'],
            ['district_id' => '15','police_station_name' => 'Tanore','bn_police_station_name' => 'তানোর'],
            ['district_id' => '15','police_station_name' => 'Bagmara','bn_police_station_name' => 'বাগমারা'],
            ['district_id' => '16','police_station_name' => 'Natore Sadar','bn_police_station_name' => 'নাটোর সদর'],
            ['district_id' => '16','police_station_name' => 'Singra','bn_police_station_name' => 'সিংড়া'],
            ['district_id' => '16','police_station_name' => 'Baraigram','bn_police_station_name' => 'বড়াইগ্রাম'],
            ['district_id' => '16','police_station_name' => 'Bagatipara','bn_police_station_name' => 'বাগাতিপাড়া'],
            ['district_id' => '16','police_station_name' => 'Lalpur','bn_police_station_name' => 'লালপুর'],
            ['district_id' => '16','police_station_name' => 'Gurudaspur','bn_police_station_name' => 'গুরুদাসপুর'],
            ['district_id' => '16','police_station_name' => 'Naldanga','bn_police_station_name' => 'নলডাঙ্গা'],
            ['district_id' => '17','police_station_name' => 'Akkelpur','bn_police_station_name' => 'আক্কেলপুর'],
            ['district_id' => '17','police_station_name' => 'Kalai','bn_police_station_name' => 'কালাই'],
            ['district_id' => '17','police_station_name' => 'Khetlal','bn_police_station_name' => 'ক্ষেতলাল'],
            ['district_id' => '17','police_station_name' => 'Panchbibi','bn_police_station_name' => 'পাঁচবিবি'],
            ['district_id' => '17','police_station_name' => 'Joypurhat Sadar','bn_police_station_name' => 'জয়পুরহাট সদর'],
            ['district_id' => '18','police_station_name' => 'Chapainawabganj Sadar','bn_police_station_name' => 'চাঁপাইনবাবগঞ্জ সদর'],
            ['district_id' => '18','police_station_name' => 'Gomostapur','bn_police_station_name' => 'গোমস্তাপুর'],
            ['district_id' => '18','police_station_name' => 'Nachol','bn_police_station_name' => 'নাচোল'],
            ['district_id' => '18','police_station_name' => 'Bholahat','bn_police_station_name' => 'ভোলাহাট'],
            ['district_id' => '18','police_station_name' => 'Shibganj','bn_police_station_name' => 'শিবগঞ্জ'],
            ['district_id' => '19','police_station_name' => 'Mohadevpur','bn_police_station_name' => 'মহাদেবপুর'],
            ['district_id' => '19','police_station_name' => 'Badalgachi','bn_police_station_name' => 'বদলগাছী'],
            ['district_id' => '19','police_station_name' => 'Patnitala','bn_police_station_name' => 'পত্নিতলা'],
            ['district_id' => '19','police_station_name' => 'Dhamoirhat','bn_police_station_name' => 'ধামইরহাট'],
            ['district_id' => '19','police_station_name' => 'Niamatpur','bn_police_station_name' => 'নিয়ামতপুর'],
            ['district_id' => '19','police_station_name' => 'Manda','bn_police_station_name' => 'মান্দা'],
            ['district_id' => '19','police_station_name' => 'Atrai','bn_police_station_name' => 'আত্রাই'],
            ['district_id' => '19','police_station_name' => 'Raninagar','bn_police_station_name' => 'রাণীনগর'],
            ['district_id' => '19','police_station_name' => 'Naogaon Sadar','bn_police_station_name' => 'নওগাঁ সদর'],
            ['district_id' => '19','police_station_name' => 'Porsha','bn_police_station_name' => 'পোরশা'],
            ['district_id' => '19','police_station_name' => 'Sapahar','bn_police_station_name' => 'সাপাহার'],
            ['district_id' => '20','police_station_name' => 'Manirampur','bn_police_station_name' => 'মণিরামপুর'],
            ['district_id' => '20','police_station_name' => 'Abhaynagar','bn_police_station_name' => 'অভয়নগর'],
            ['district_id' => '20','police_station_name' => 'Bagherpara','bn_police_station_name' => 'বাঘারপাড়া'],
            ['district_id' => '20','police_station_name' => 'Chougachha','bn_police_station_name' => 'চৌগাছা'],
            ['district_id' => '20','police_station_name' => 'Jhikargacha','bn_police_station_name' => 'ঝিকরগাছা'],
            ['district_id' => '20','police_station_name' => 'Keshabpur','bn_police_station_name' => 'কেশবপুর'],
            ['district_id' => '20','police_station_name' => 'Jessore Sadar','bn_police_station_name' => 'যশোর সদর'],
            ['district_id' => '20','police_station_name' => 'Sharsha','bn_police_station_name' => 'শার্শা'],
            ['district_id' => '21','police_station_name' => 'Assasuni','bn_police_station_name' => 'আশাশুনি'],
            ['district_id' => '21','police_station_name' => 'Debhata','bn_police_station_name' => 'দেবহাটা'],
            ['district_id' => '21','police_station_name' => 'Kalaroa','bn_police_station_name' => 'কলারোয়া'],
            ['district_id' => '21','police_station_name' => 'Satkhira Sadar','bn_police_station_name' => 'সাতক্ষীরা সদর'],
            ['district_id' => '21','police_station_name' => 'Shyamnagar','bn_police_station_name' => 'শ্যামনগর'],
            ['district_id' => '21','police_station_name' => 'Tala','bn_police_station_name' => 'তালা'],
            ['district_id' => '21','police_station_name' => 'Kaliganj','bn_police_station_name' => 'কালিগঞ্জ'],
            ['district_id' => '22','police_station_name' => 'Mujibnagar','bn_police_station_name' => 'মুজিবনগর'],
            ['district_id' => '22','police_station_name' => 'Meherpur Sadar','bn_police_station_name' => 'মেহেরপুর সদর'],
            ['district_id' => '22','police_station_name' => 'Gangni','bn_police_station_name' => 'গাংনী'],
            ['district_id' => '23','police_station_name' => 'Narail Sadar','bn_police_station_name' => 'নড়াইল সদর'],
            ['district_id' => '23','police_station_name' => 'Lohagara','bn_police_station_name' => 'লোহাগড়া'],
            ['district_id' => '23','police_station_name' => 'Kalia','bn_police_station_name' => 'কালিয়া'],
            ['district_id' => '24','police_station_name' => 'Chuadanga Sadar','bn_police_station_name' => 'চুয়াডাঙ্গা সদর'],
            ['district_id' => '24','police_station_name' => 'Alamdanga','bn_police_station_name' => 'আলমডাঙ্গা'],
            ['district_id' => '24','police_station_name' => 'Damurhuda','bn_police_station_name' => 'দামুড়হুদা'],
            ['district_id' => '24','police_station_name' => 'Jibannagar','bn_police_station_name' => 'জীবননগর'],
            ['district_id' => '25','police_station_name' => 'Kushtia Sadar','bn_police_station_name' => 'কুষ্টিয়া সদর'],
            ['district_id' => '25','police_station_name' => 'Kumarkhali','bn_police_station_name' => 'কুমারখালী'],
            ['district_id' => '25','police_station_name' => 'Khoksa','bn_police_station_name' => 'খোকসা'],
            ['district_id' => '25','police_station_name' => 'Mirpur','bn_police_station_name' => 'মিরপুর'],
            ['district_id' => '25','police_station_name' => 'Daulatpur','bn_police_station_name' => 'দৌলতপুর'],
            ['district_id' => '25','police_station_name' => 'Bheramara','bn_police_station_name' => 'ভেড়ামারা'],
            ['district_id' => '26','police_station_name' => 'Shalikha','bn_police_station_name' => 'শালিখা'],
            ['district_id' => '26','police_station_name' => 'Sreepur','bn_police_station_name' => 'শ্রীপুর'],
            ['district_id' => '26','police_station_name' => 'Magura Sadar','bn_police_station_name' => 'মাগুরা সদর'],
            ['district_id' => '26','police_station_name' => 'Mohammadpur','bn_police_station_name' => 'মহম্মদপুর'],
            ['district_id' => '27','police_station_name' => 'Paikgasa','bn_police_station_name' => 'পাইকগাছা'],
            ['district_id' => '27','police_station_name' => 'Fultola','bn_police_station_name' => 'ফুলতলা'],
            ['district_id' => '27','police_station_name' => 'Digholia','bn_police_station_name' => 'দিঘলিয়া'],
            ['district_id' => '27','police_station_name' => 'Rupsha','bn_police_station_name' => 'রূপসা'],
            ['district_id' => '27','police_station_name' => 'Terokhada','bn_police_station_name' => 'তেরখাদা'],
            ['district_id' => '27','police_station_name' => 'Dumuria','bn_police_station_name' => 'ডুমুরিয়া'],
            ['district_id' => '27','police_station_name' => 'Botiaghata','bn_police_station_name' => 'বটিয়াঘাটা'],
            ['district_id' => '27','police_station_name' => 'Dakop','bn_police_station_name' => 'দাকোপ'],
            ['district_id' => '27','police_station_name' => 'Koyra','bn_police_station_name' => 'কয়রা'],
            ['district_id' => '28','police_station_name' => 'Fakirhat','bn_police_station_name' => 'ফকিরহাট'],
            ['district_id' => '28','police_station_name' => 'Bagerhat Sadar','bn_police_station_name' => 'বাগেরহাট সদর'],
            ['district_id' => '28','police_station_name' => 'Mollahat','bn_police_station_name' => 'মোল্লাহাট'],
            ['district_id' => '28','police_station_name' => 'Sarankhola','bn_police_station_name' => 'শরণখোলা'],
            ['district_id' => '28','police_station_name' => 'Rampal','bn_police_station_name' => 'রামপাল'],
            ['district_id' => '28','police_station_name' => 'Morrelganj','bn_police_station_name' => 'মোড়েলগঞ্জ'],
            ['district_id' => '28','police_station_name' => 'Kachua','bn_police_station_name' => 'কচুয়া'],
            ['district_id' => '28','police_station_name' => 'Mongla','bn_police_station_name' => 'মোংলা'],
            ['district_id' => '28','police_station_name' => 'Chitalmari','bn_police_station_name' => 'চিতলমারী'],
            ['district_id' => '29','police_station_name' => 'Jhenaidah Sadar','bn_police_station_name' => 'ঝিনাইদহ সদর'],
            ['district_id' => '29','police_station_name' => 'Shailkupa','bn_police_station_name' => 'শৈলকুপা'],
            ['district_id' => '29','police_station_name' => 'Harinakundu','bn_police_station_name' => 'হরিণাকুন্ডু'],
            ['district_id' => '29','police_station_name' => 'Kaliganj','bn_police_station_name' => 'কালীগঞ্জ'],
            ['district_id' => '29','police_station_name' => 'Kotchandpur','bn_police_station_name' => 'কোটচাঁদপুর'],
            ['district_id' => '29','police_station_name' => 'Moheshpur','bn_police_station_name' => 'মহেশপুর'],
            ['district_id' => '30','police_station_name' => 'Jhalakathi Sadar','bn_police_station_name' => 'ঝালকাঠি সদর'],
            ['district_id' => '30','police_station_name' => 'Kathalia','bn_police_station_name' => 'কাঠালিয়া'],
            ['district_id' => '30','police_station_name' => 'Nalchity','bn_police_station_name' => 'নলছিটি'],
            ['district_id' => '30','police_station_name' => 'Rajapur','bn_police_station_name' => 'রাজাপুর'],
            ['district_id' => '31','police_station_name' => 'Bauphal','bn_police_station_name' => 'বাউফল'],
            ['district_id' => '31','police_station_name' => 'Patuakhali Sadar','bn_police_station_name' => 'পটুয়াখালী সদর'],
            ['district_id' => '31','police_station_name' => 'Dumki','bn_police_station_name' => 'দুমকি'],
            ['district_id' => '31','police_station_name' => 'Dashmina','bn_police_station_name' => 'দশমিনা'],
            ['district_id' => '31','police_station_name' => 'Kalapara','bn_police_station_name' => 'কলাপাড়া'],
            ['district_id' => '31','police_station_name' => 'Mirzaganj','bn_police_station_name' => 'মির্জাগঞ্জ'],
            ['district_id' => '31','police_station_name' => 'Galachipa','bn_police_station_name' => 'গলাচিপা'],
            ['district_id' => '31','police_station_name' => 'Rangabali','bn_police_station_name' => 'রাঙ্গাবালী'],
            ['district_id' => '32','police_station_name' => 'Pirojpur Sadar','bn_police_station_name' => 'পিরোজপুর সদর'],
            ['district_id' => '32','police_station_name' => 'Nazirpur','bn_police_station_name' => 'নাজিরপুর'],
            ['district_id' => '32','police_station_name' => 'Kawkhali','bn_police_station_name' => 'কাউখালী'],
            ['district_id' => '32','police_station_name' => 'Zianagar','bn_police_station_name' => 'জিয়ানগর'],
            ['district_id' => '32','police_station_name' => 'Bhandaria','bn_police_station_name' => 'ভান্ডারিয়া'],
            ['district_id' => '32','police_station_name' => 'Mathbaria','bn_police_station_name' => 'মঠবাড়ীয়া'],
            ['district_id' => '32','police_station_name' => 'Nesarabad','bn_police_station_name' => 'নেছারাবাদ'],
            ['district_id' => '33','police_station_name' => 'Barisal Sadar','bn_police_station_name' => 'বরিশাল সদর'],
            ['district_id' => '33','police_station_name' => 'Bakerganj','bn_police_station_name' => 'বাকেরগঞ্জ'],
            ['district_id' => '33','police_station_name' => 'Babuganj','bn_police_station_name' => 'বাবুগঞ্জ'],
            ['district_id' => '33','police_station_name' => 'Wazirpur','bn_police_station_name' => 'উজিরপুর'],
            ['district_id' => '33','police_station_name' => 'Banaripara','bn_police_station_name' => 'বানারীপাড়া'],
            ['district_id' => '33','police_station_name' => 'Gournadi','bn_police_station_name' => 'গৌরনদী'],
            ['district_id' => '33','police_station_name' => 'Agailjhara','bn_police_station_name' => 'আগৈলঝাড়া'],
            ['district_id' => '33','police_station_name' => 'Mehendiganj','bn_police_station_name' => 'মেহেন্দিগঞ্জ'],
            ['district_id' => '33','police_station_name' => 'Muladi','bn_police_station_name' => 'মুলাদী'],
            ['district_id' => '33','police_station_name' => 'Hizla','bn_police_station_name' => 'হিজলা'],
            ['district_id' => '34','police_station_name' => 'Bhola Sadar','bn_police_station_name' => 'ভোলা সদর'],
            ['district_id' => '34','police_station_name' => 'Borhan Sddin','bn_police_station_name' => 'বোরহান উদ্দিন'],
            ['district_id' => '34','police_station_name' => 'Charfesson','bn_police_station_name' => 'চরফ্যাশন'],
            ['district_id' => '34','police_station_name' => 'Doulatkhan','bn_police_station_name' => 'দৌলতখান'],
            ['district_id' => '34','police_station_name' => 'Monpura','bn_police_station_name' => 'মনপুরা'],
            ['district_id' => '34','police_station_name' => 'Tazumuddin','bn_police_station_name' => 'তজুমদ্দিন'],
            ['district_id' => '34','police_station_name' => 'Lalmohan','bn_police_station_name' => 'লালমোহন'],
            ['district_id' => '35','police_station_name' => 'Amtali','bn_police_station_name' => 'আমতলী'],
            ['district_id' => '35','police_station_name' => 'Barguna Sadar','bn_police_station_name' => 'বরগুনা সদর'],
            ['district_id' => '35','police_station_name' => 'Betagi','bn_police_station_name' => 'বেতাগী'],
            ['district_id' => '35','police_station_name' => 'Bamna','bn_police_station_name' => 'বামনা'],
            ['district_id' => '35','police_station_name' => 'Pathorghata','bn_police_station_name' => 'পাথরঘাটা'],
            ['district_id' => '35','police_station_name' => 'Taltali','bn_police_station_name' => 'তালতলি'],
            ['district_id' => '36','police_station_name' => 'Balaganj','bn_police_station_name' => 'বালাগঞ্জ'],
            ['district_id' => '36','police_station_name' => 'Beanibazar','bn_police_station_name' => 'বিয়ানীবাজার'],
            ['district_id' => '36','police_station_name' => 'Bishwanath','bn_police_station_name' => 'বিশ্বনাথ'],
            ['district_id' => '36','police_station_name' => 'Companiganj','bn_police_station_name' => 'কোম্পানীগঞ্জ'],
            ['district_id' => '36','police_station_name' => 'Fenchuganj','bn_police_station_name' => 'ফেঞ্চুগঞ্জ'],
            ['district_id' => '36','police_station_name' => 'Golapganj','bn_police_station_name' => 'গোলাপগঞ্জ'],
            ['district_id' => '36','police_station_name' => 'Gowainghat','bn_police_station_name' => 'গোয়াইনঘাট'],
            ['district_id' => '36','police_station_name' => 'Jaintiapur','bn_police_station_name' => 'জৈন্তাপুর'],
            ['district_id' => '36','police_station_name' => 'Kanaighat','bn_police_station_name' => 'কানাইঘাট'],
            ['district_id' => '36','police_station_name' => 'Sylhet Sadar','bn_police_station_name' => 'সিলেট সদর'],
            ['district_id' => '36','police_station_name' => 'Zakiganj','bn_police_station_name' => 'জকিগঞ্জ'],
            ['district_id' => '36','police_station_name' => 'Dakshinsurma','bn_police_station_name' => 'দক্ষিণ সুরমা'],
            ['district_id' => '36','police_station_name' => 'Osmaninagar','bn_police_station_name' => 'ওসমানী নগর'],
            ['district_id' => '37','police_station_name' => 'Barlekha','bn_police_station_name' => 'বড়লেখা'],
            ['district_id' => '37','police_station_name' => 'Kamolganj','bn_police_station_name' => 'কমলগঞ্জ'],
            ['district_id' => '37','police_station_name' => 'Kulaura','bn_police_station_name' => 'কুলাউড়া'],
            ['district_id' => '37','police_station_name' => 'Moulvibazar Sadar','bn_police_station_name' => 'মৌলভীবাজার সদর'],
            ['district_id' => '37','police_station_name' => 'Rajnagar','bn_police_station_name' => 'রাজনগর'],
            ['district_id' => '37','police_station_name' => 'Sreemangal','bn_police_station_name' => 'শ্রীমঙ্গল'],
            ['district_id' => '37','police_station_name' => 'Juri','bn_police_station_name' => 'জুড়ী'],
            ['district_id' => '38','police_station_name' => 'Nabiganj','bn_police_station_name' => 'নবীগঞ্জ'],
            ['district_id' => '38','police_station_name' => 'Bahubal','bn_police_station_name' => 'বাহুবল'],
            ['district_id' => '38','police_station_name' => 'Ajmiriganj','bn_police_station_name' => 'আজমিরীগঞ্জ'],
            ['district_id' => '38','police_station_name' => 'Baniachong','bn_police_station_name' => 'বানিয়াচং'],
            ['district_id' => '38','police_station_name' => 'Lakhai','bn_police_station_name' => 'লাখাই'],
            ['district_id' => '38','police_station_name' => 'Chunarughat','bn_police_station_name' => 'চুনারুঘাট'],
            ['district_id' => '38','police_station_name' => 'Habiganj Sadar','bn_police_station_name' => 'হবিগঞ্জ সদর'],
            ['district_id' => '38','police_station_name' => 'Madhabpur','bn_police_station_name' => 'মাধবপুর'],
            ['district_id' => '39','police_station_name' => 'Sunamganj Sadar','bn_police_station_name' => 'সুনামগঞ্জ সদর'],
            ['district_id' => '39','police_station_name' => 'South Sunamganj','bn_police_station_name' => 'দক্ষিণ সুনামগঞ্জ'],
            ['district_id' => '39','police_station_name' => 'Bishwambarpur','bn_police_station_name' => 'বিশ্বম্ভরপুর'],
            ['district_id' => '39','police_station_name' => 'Chhatak','bn_police_station_name' => 'ছাতক'],
            ['district_id' => '39','police_station_name' => 'Jagannathpur','bn_police_station_name' => 'জগন্নাথপুর'],
            ['district_id' => '39','police_station_name' => 'Dowarabazar','bn_police_station_name' => 'দোয়ারাবাজার'],
            ['district_id' => '39','police_station_name' => 'Tahirpur','bn_police_station_name' => 'তাহিরপুর'],
            ['district_id' => '39','police_station_name' => 'Dharmapasha','bn_police_station_name' => 'ধর্মপাশা'],
            ['district_id' => '39','police_station_name' => 'Jamalganj','bn_police_station_name' => 'জামালগঞ্জ'],
            ['district_id' => '39','police_station_name' => 'Shalla','bn_police_station_name' => 'শাল্লা'],
            ['district_id' => '39','police_station_name' => 'Derai','bn_police_station_name' => 'দিরাই'],
            ['district_id' => '40','police_station_name' => 'Belabo','bn_police_station_name' => 'বেলাবো'],
            ['district_id' => '40','police_station_name' => 'Monohardi','bn_police_station_name' => 'মনোহরদী'],
            ['district_id' => '40','police_station_name' => 'Narsingdi Sadar','bn_police_station_name' => 'নরসিংদী সদর'],
            ['district_id' => '40','police_station_name' => 'Palash','bn_police_station_name' => 'পলাশ'],
            ['district_id' => '40','police_station_name' => 'Raipura','bn_police_station_name' => 'রায়পুরা'],
            ['district_id' => '40','police_station_name' => 'Shibpur','bn_police_station_name' => 'শিবপুর'],
            ['district_id' => '41','police_station_name' => 'Kaliganj','bn_police_station_name' => 'কালীগঞ্জ'],
            ['district_id' => '41','police_station_name' => 'Kaliakair','bn_police_station_name' => 'কালিয়াকৈর'],
            ['district_id' => '41','police_station_name' => 'Kapasia','bn_police_station_name' => 'কাপাসিয়া'],
            ['district_id' => '41','police_station_name' => 'Gazipur Sadar','bn_police_station_name' => 'গাজীপুর সদর'],
            ['district_id' => '41','police_station_name' => 'Sreepur','bn_police_station_name' => 'শ্রীপুর'],
            ['district_id' => '42','police_station_name' => 'Shariatpur Sadar','bn_police_station_name' => 'শরিয়তপুর সদর'],
            ['district_id' => '42','police_station_name' => 'Naria','bn_police_station_name' => 'নড়িয়া'],
            ['district_id' => '42','police_station_name' => 'Zajira','bn_police_station_name' => 'জাজিরা'],
            ['district_id' => '42','police_station_name' => 'Gosairhat','bn_police_station_name' => 'গোসাইরহাট'],
            ['district_id' => '42','police_station_name' => 'Bhedarganj','bn_police_station_name' => 'ভেদরগঞ্জ'],
            ['district_id' => '42','police_station_name' => 'Damudya','bn_police_station_name' => 'ডামুড্যা'],
            ['district_id' => '43','police_station_name' => 'Araihazar','bn_police_station_name' => 'আড়াইহাজার'],
            ['district_id' => '43','police_station_name' => 'Bandar','bn_police_station_name' => 'বন্দর'],
            ['district_id' => '43','police_station_name' => 'Narayanganj Sadar','bn_police_station_name' => 'নারায়নগঞ্জ সদর'],
            ['district_id' => '43','police_station_name' => 'Rupganj','bn_police_station_name' => 'রূপগঞ্জ'],
            ['district_id' => '43','police_station_name' => 'Sonargaon','bn_police_station_name' => 'সোনারগাঁ'],
            ['district_id' => '44','police_station_name' => 'Basail','bn_police_station_name' => 'বাসাইল'],
            ['district_id' => '44','police_station_name' => 'Bhuapur','bn_police_station_name' => 'ভুয়াপুর'],
            ['district_id' => '44','police_station_name' => 'Delduar','bn_police_station_name' => 'দেলদুয়ার'],
            ['district_id' => '44','police_station_name' => 'Ghatail','bn_police_station_name' => 'ঘাটাইল'],
            ['district_id' => '44','police_station_name' => 'Gopalpur','bn_police_station_name' => 'গোপালপুর'],
            ['district_id' => '44','police_station_name' => 'Madhupur','bn_police_station_name' => 'মধুপুর'],
            ['district_id' => '44','police_station_name' => 'Mirzapur','bn_police_station_name' => 'মির্জাপুর'],
            ['district_id' => '44','police_station_name' => 'Nagarpur','bn_police_station_name' => 'নাগরপুর'],
            ['district_id' => '44','police_station_name' => 'Sakhipur','bn_police_station_name' => 'সখিপুর'],
            ['district_id' => '44','police_station_name' => 'Tangail Sadar','bn_police_station_name' => 'টাঙ্গাইল সদর'],
            ['district_id' => '44','police_station_name' => 'Kalihati','bn_police_station_name' => 'কালিহাতী'],
            ['district_id' => '44','police_station_name' => 'Dhanbari','bn_police_station_name' => 'ধনবাড়ী'],
            ['district_id' => '45','police_station_name' => 'Itna','bn_police_station_name' => 'ইটনা'],
            ['district_id' => '45','police_station_name' => 'Katiadi','bn_police_station_name' => 'কটিয়াদী'],
            ['district_id' => '45','police_station_name' => 'Bhairab','bn_police_station_name' => 'ভৈরব'],
            ['district_id' => '45','police_station_name' => 'Tarail','bn_police_station_name' => 'তাড়াইল'],
            ['district_id' => '45','police_station_name' => 'Hossainpur','bn_police_station_name' => 'হোসেনপুর'],
            ['district_id' => '45','police_station_name' => 'Pakundia','bn_police_station_name' => 'পাকুন্দিয়া'],
            ['district_id' => '45','police_station_name' => 'Kuliarchar','bn_police_station_name' => 'কুলিয়ারচর'],
            ['district_id' => '45','police_station_name' => 'Kishoreganj Sadar','bn_police_station_name' => 'কিশোরগঞ্জ সদর'],
            ['district_id' => '45','police_station_name' => 'Karimgonj','bn_police_station_name' => 'করিমগঞ্জ'],
            ['district_id' => '45','police_station_name' => 'Bajitpur','bn_police_station_name' => 'বাজিতপুর'],
            ['district_id' => '45','police_station_name' => 'Austagram','bn_police_station_name' => 'অষ্টগ্রাম'],
            ['district_id' => '45','police_station_name' => 'Mithamoin','bn_police_station_name' => 'মিঠামইন'],
            ['district_id' => '45','police_station_name' => 'Nikli','bn_police_station_name' => 'নিকলী'],
            ['district_id' => '46','police_station_name' => 'Harirampur','bn_police_station_name' => 'হরিরামপুর'],
            ['district_id' => '46','police_station_name' => 'Saturia','bn_police_station_name' => 'সাটুরিয়া'],
            ['district_id' => '46','police_station_name' => 'Manikganj Sadar','bn_police_station_name' => 'মানিকগঞ্জ সদর'],
            ['district_id' => '46','police_station_name' => 'Gior','bn_police_station_name' => 'ঘিওর'],
            ['district_id' => '46','police_station_name' => 'Shibaloy','bn_police_station_name' => 'শিবালয়'],
            ['district_id' => '46','police_station_name' => 'Doulatpur','bn_police_station_name' => 'দৌলতপুর'],
            ['district_id' => '46','police_station_name' => 'Singiar','bn_police_station_name' => 'সিংগাইর'],
            ['district_id' => '47','police_station_name' => 'Savar','bn_police_station_name' => 'সাভার'],
            ['district_id' => '47','police_station_name' => 'Dhamrai','bn_police_station_name' => 'ধামরাই'],
            ['district_id' => '47','police_station_name' => 'Keraniganj','bn_police_station_name' => 'কেরাণীগঞ্জ'],
            ['district_id' => '47','police_station_name' => 'Nawabganj','bn_police_station_name' => 'নবাবগঞ্জ'],
            ['district_id' => '47','police_station_name' => 'Dohar','bn_police_station_name' => 'দোহার'],
            ['district_id' => '48','police_station_name' => 'Munshiganj Sadar','bn_police_station_name' => 'মুন্সিগঞ্জ সদর'],
            ['district_id' => '48','police_station_name' => 'Sreenagar','bn_police_station_name' => 'শ্রীনগর'],
            ['district_id' => '48','police_station_name' => 'Sirajdikhan','bn_police_station_name' => 'সিরাজদিখান'],
            ['district_id' => '48','police_station_name' => 'Louhajanj','bn_police_station_name' => 'লৌহজং'],
            ['district_id' => '48','police_station_name' => 'Gajaria','bn_police_station_name' => 'গজারিয়া'],
            ['district_id' => '48','police_station_name' => 'Tongibari','bn_police_station_name' => 'টংগীবাড়ি'],
            ['district_id' => '49','police_station_name' => 'Rajbari Sadar','bn_police_station_name' => 'রাজবাড়ী সদর'],
            ['district_id' => '49','police_station_name' => 'Goalanda','bn_police_station_name' => 'গোয়ালন্দ'],
            ['district_id' => '49','police_station_name' => 'Pangsa','bn_police_station_name' => 'পাংশা'],
            ['district_id' => '49','police_station_name' => 'Baliakandi','bn_police_station_name' => 'বালিয়াকান্দি'],
            ['district_id' => '49','police_station_name' => 'Kalukhali','bn_police_station_name' => 'কালুখালী'],
            ['district_id' => '50','police_station_name' => 'Madaripur Sadar','bn_police_station_name' => 'মাদারীপুর সদর'],
            ['district_id' => '50','police_station_name' => 'Shibchar','bn_police_station_name' => 'শিবচর'],
            ['district_id' => '50','police_station_name' => 'Kalkini','bn_police_station_name' => 'কালকিনি'],
            ['district_id' => '50','police_station_name' => 'Rajoir','bn_police_station_name' => 'রাজৈর'],
            ['district_id' => '51','police_station_name' => 'Gopalganj Sadar','bn_police_station_name' => 'গোপালগঞ্জ সদর'],
            ['district_id' => '51','police_station_name' => 'Kashiani','bn_police_station_name' => 'কাশিয়ানী'],
            ['district_id' => '51','police_station_name' => 'Tungipara','bn_police_station_name' => 'টুংগীপাড়া'],
            ['district_id' => '51','police_station_name' => 'Kotalipara','bn_police_station_name' => 'কোটালীপাড়া'],
            ['district_id' => '51','police_station_name' => 'Muksudpur','bn_police_station_name' => 'মুকসুদপুর'],
            ['district_id' => '52','police_station_name' => 'Faridpur Sadar','bn_police_station_name' => 'ফরিদপুর সদর'],
            ['district_id' => '52','police_station_name' => 'Alfadanga','bn_police_station_name' => 'আলফাডাঙ্গা'],
            ['district_id' => '52','police_station_name' => 'Boalmari','bn_police_station_name' => 'বোয়ালমারী'],
            ['district_id' => '52','police_station_name' => 'Sadarpur','bn_police_station_name' => 'সদরপুর'],
            ['district_id' => '52','police_station_name' => 'Nagarkanda','bn_police_station_name' => 'নগরকান্দা'],
            ['district_id' => '52','police_station_name' => 'Bhanga','bn_police_station_name' => 'ভাঙ্গা'],
            ['district_id' => '52','police_station_name' => 'Charbhadrasan','bn_police_station_name' => 'চরভদ্রাসন'],
            ['district_id' => '52','police_station_name' => 'Madhukhali','bn_police_station_name' => 'মধুখালী'],
            ['district_id' => '52','police_station_name' => 'Saltha','bn_police_station_name' => 'সালথা'],
            ['district_id' => '53','police_station_name' => 'Panchagarh Sadar','bn_police_station_name' => 'পঞ্চগড় সদর'],
            ['district_id' => '53','police_station_name' => 'Debiganj','bn_police_station_name' => 'দেবীগঞ্জ'],
            ['district_id' => '53','police_station_name' => 'Boda','bn_police_station_name' => 'বোদা'],
            ['district_id' => '53','police_station_name' => 'Atwari','bn_police_station_name' => 'আটোয়ারী'],
            ['district_id' => '53','police_station_name' => 'Tetulia','bn_police_station_name' => 'তেতুলিয়া'],
            ['district_id' => '54','police_station_name' => 'Nawabganj','bn_police_station_name' => 'নবাবগঞ্জ'],
            ['district_id' => '54','police_station_name' => 'Birganj','bn_police_station_name' => 'বীরগঞ্জ'],
            ['district_id' => '54','police_station_name' => 'Ghoraghat','bn_police_station_name' => 'ঘোড়াঘাট'],
            ['district_id' => '54','police_station_name' => 'Birampur','bn_police_station_name' => 'বিরামপুর'],
            ['district_id' => '54','police_station_name' => 'Parbatipur','bn_police_station_name' => 'পার্বতীপুর'],
            ['district_id' => '54','police_station_name' => 'Bochaganj','bn_police_station_name' => 'বোচাগঞ্জ'],
            ['district_id' => '54','police_station_name' => 'Kaharol','bn_police_station_name' => 'কাহারোল'],
            ['district_id' => '54','police_station_name' => 'Fulbari','bn_police_station_name' => 'ফুলবাড়ী'],
            ['district_id' => '54','police_station_name' => 'Dinajpur Sadar','bn_police_station_name' => 'দিনাজপুর সদর'],
            ['district_id' => '54','police_station_name' => 'Hakimpur','bn_police_station_name' => 'হাকিমপুর'],
            ['district_id' => '54','police_station_name' => 'Khansama','bn_police_station_name' => 'খানসামা'],
            ['district_id' => '54','police_station_name' => 'Birol','bn_police_station_name' => 'বিরল'],
            ['district_id' => '54','police_station_name' => 'Chirirbandar','bn_police_station_name' => 'চিরিরবন্দর'],
            ['district_id' => '55','police_station_name' => 'Lalmonirhat Sadar','bn_police_station_name' => 'লালমনিরহাট সদর'],
            ['district_id' => '55','police_station_name' => 'Kaliganj','bn_police_station_name' => 'কালীগঞ্জ'],
            ['district_id' => '55','police_station_name' => 'Hatibandha','bn_police_station_name' => 'হাতীবান্ধা'],
            ['district_id' => '55','police_station_name' => 'Patgram','bn_police_station_name' => 'পাটগ্রাম'],
            ['district_id' => '55','police_station_name' => 'Aditmari','bn_police_station_name' => 'আদিতমারী'],
            ['district_id' => '56','police_station_name' => 'Syedpur','bn_police_station_name' => 'সৈয়দপুর'],
            ['district_id' => '56','police_station_name' => 'Domar','bn_police_station_name' => 'ডোমার'],
            ['district_id' => '56','police_station_name' => 'Dimla','bn_police_station_name' => 'ডিমলা'],
            ['district_id' => '56','police_station_name' => 'Jaldhaka','bn_police_station_name' => 'জলঢাকা'],
            ['district_id' => '56','police_station_name' => 'Kishorganj','bn_police_station_name' => 'কিশোরগঞ্জ'],
            ['district_id' => '56','police_station_name' => 'Nilphamari Sadar','bn_police_station_name' => 'নীলফামারী সদর'],
            ['district_id' => '57','police_station_name' => 'Sadullapur','bn_police_station_name' => 'সাদুল্লাপুর'],
            ['district_id' => '57','police_station_name' => 'Gaibandha Sadar','bn_police_station_name' => 'গাইবান্ধা সদর'],
            ['district_id' => '57','police_station_name' => 'Palashbari','bn_police_station_name' => 'পলাশবাড়ী'],
            ['district_id' => '57','police_station_name' => 'Saghata','bn_police_station_name' => 'সাঘাটা'],
            ['district_id' => '57','police_station_name' => 'Gobindaganj','bn_police_station_name' => 'গোবিন্দগঞ্জ'],
            ['district_id' => '57','police_station_name' => 'Sundarganj','bn_police_station_name' => 'সুন্দরগঞ্জ'],
            ['district_id' => '57','police_station_name' => 'Phulchari','bn_police_station_name' => 'ফুলছড়ি'],
            ['district_id' => '58','police_station_name' => 'Thakurgaon Sadar','bn_police_station_name' => 'ঠাকুরগাঁও সদর'],
            ['district_id' => '58','police_station_name' => 'Pirganj','bn_police_station_name' => 'পীরগঞ্জ'],
            ['district_id' => '58','police_station_name' => 'Ranisankail','bn_police_station_name' => 'রাণীশংকৈল'],
            ['district_id' => '58','police_station_name' => 'Haripur','bn_police_station_name' => 'হরিপুর'],
            ['district_id' => '58','police_station_name' => 'Baliadangi','bn_police_station_name' => 'বালিয়াডাঙ্গী'],
            ['district_id' => '59','police_station_name' => 'Rangpur Sadar','bn_police_station_name' => 'রংপুর সদর'],
            ['district_id' => '59','police_station_name' => 'Gangachara','bn_police_station_name' => 'গংগাচড়া'],
            ['district_id' => '59','police_station_name' => 'Taragonj','bn_police_station_name' => 'তারাগঞ্জ'],
            ['district_id' => '59','police_station_name' => 'Badargonj','bn_police_station_name' => 'বদরগঞ্জ'],
            ['district_id' => '59','police_station_name' => 'Mithapukur','bn_police_station_name' => 'মিঠাপুকুর'],
            ['district_id' => '59','police_station_name' => 'Pirgonj','bn_police_station_name' => 'পীরগঞ্জ'],
            ['district_id' => '59','police_station_name' => 'Kaunia','bn_police_station_name' => 'কাউনিয়া'],
            ['district_id' => '59','police_station_name' => 'Pirgacha','bn_police_station_name' => 'পীরগাছা'],
            ['district_id' => '60','police_station_name' => 'Kurigram Sadar','bn_police_station_name' => 'কুড়িগ্রাম সদর'],
            ['district_id' => '60','police_station_name' => 'Nageshwari','bn_police_station_name' => 'নাগেশ্বরী'],
            ['district_id' => '60','police_station_name' => 'Bhurungamari','bn_police_station_name' => 'ভুরুঙ্গামারী'],
            ['district_id' => '60','police_station_name' => 'Phulbari','bn_police_station_name' => 'ফুলবাড়ী'],
            ['district_id' => '60','police_station_name' => 'Rajarhat','bn_police_station_name' => 'রাজারহাট'],
            ['district_id' => '60','police_station_name' => 'Ulipur','bn_police_station_name' => 'উলিপুর'],
            ['district_id' => '60','police_station_name' => 'Chilmari','bn_police_station_name' => 'চিলমারী'],
            ['district_id' => '60','police_station_name' => 'Rowmari','bn_police_station_name' => 'রৌমারী'],
            ['district_id' => '60','police_station_name' => 'Charrajibpur','bn_police_station_name' => 'চর রাজিবপুর'],
            ['district_id' => '61','police_station_name' => 'Sherpur Sadar','bn_police_station_name' => 'শেরপুর সদর'],
            ['district_id' => '61','police_station_name' => 'Nalitabari','bn_police_station_name' => 'নালিতাবাড়ী'],
            ['district_id' => '61','police_station_name' => 'Sreebordi','bn_police_station_name' => 'শ্রীবরদী'],
            ['district_id' => '61','police_station_name' => 'Nokla','bn_police_station_name' => 'নকলা'],
            ['district_id' => '61','police_station_name' => 'Jhenaigati','bn_police_station_name' => 'ঝিনাইগাতী'],
            ['district_id' => '62','police_station_name' => 'Fulbaria','bn_police_station_name' => 'ফুলবাড়ীয়া'],
            ['district_id' => '62','police_station_name' => 'Trishal','bn_police_station_name' => 'ত্রিশাল'],
            ['district_id' => '62','police_station_name' => 'Bhaluka','bn_police_station_name' => 'ভালুকা'],
            ['district_id' => '62','police_station_name' => 'Muktagacha','bn_police_station_name' => 'মুক্তাগাছা'],
            ['district_id' => '62','police_station_name' => 'Mymensingh Sadar','bn_police_station_name' => 'ময়মনসিংহ সদর'],
            ['district_id' => '62','police_station_name' => 'Dhobaura','bn_police_station_name' => 'ধোবাউড়া'],
            ['district_id' => '62','police_station_name' => 'Phulpur','bn_police_station_name' => 'ফুলপুর'],
            ['district_id' => '62','police_station_name' => 'Haluaghat','bn_police_station_name' => 'হালুয়াঘাট'],
            ['district_id' => '62','police_station_name' => 'Gouripur','bn_police_station_name' => 'গৌরীপুর'],
            ['district_id' => '62','police_station_name' => 'Gafargaon','bn_police_station_name' => 'গফরগাঁও'],
            ['district_id' => '62','police_station_name' => 'Iswarganj','bn_police_station_name' => 'ঈশ্বরগঞ্জ'],
            ['district_id' => '62','police_station_name' => 'Nandail','bn_police_station_name' => 'নান্দাইল'],
            ['district_id' => '62','police_station_name' => 'Tarakanda','bn_police_station_name' => 'তারাকান্দা'],
            ['district_id' => '63','police_station_name' => 'Jamalpur Sadar','bn_police_station_name' => 'জামালপুর সদর'],
            ['district_id' => '63','police_station_name' => 'Melandah','bn_police_station_name' => 'মেলান্দহ'],
            ['district_id' => '63','police_station_name' => 'Islampur','bn_police_station_name' => 'ইসলামপুর'],
            ['district_id' => '63','police_station_name' => 'Dewangonj','bn_police_station_name' => 'দেওয়ানগঞ্জ'],
            ['district_id' => '63','police_station_name' => 'Sarishabari','bn_police_station_name' => 'সরিষাবাড়ী'],
            ['district_id' => '63','police_station_name' => 'Madarganj','bn_police_station_name' => 'মাদারগঞ্জ'],
            ['district_id' => '63','police_station_name' => 'Bokshiganj','bn_police_station_name' => 'বকশীগঞ্জ'],
            ['district_id' => '64','police_station_name' => 'Barhatta','bn_police_station_name' => 'বারহাট্টা'],
            ['district_id' => '64','police_station_name' => 'Durgapur','bn_police_station_name' => 'দুর্গাপুর'],
            ['district_id' => '64','police_station_name' => 'Kendua','bn_police_station_name' => 'কেন্দুয়া'],
            ['district_id' => '64','police_station_name' => 'Atpara','bn_police_station_name' => 'আটপাড়া'],
            ['district_id' => '64','police_station_name' => 'Madan','bn_police_station_name' => 'মদন'],
            ['district_id' => '64','police_station_name' => 'Khaliajuri','bn_police_station_name' => 'খালিয়াজুরী'],
            ['district_id' => '64','police_station_name' => 'Kalmakanda','bn_police_station_name' => 'কলমাকান্দা'],
            ['district_id' => '64','police_station_name' => 'Mohongonj','bn_police_station_name' => 'মোহনগঞ্জ'],
            ['district_id' => '64','police_station_name' => 'Purbadhala','bn_police_station_name' => 'পূর্বধলা'],
            ['district_id' => '64','police_station_name' => 'Netrokona Sadar','bn_police_station_name' => 'নেত্রকোণা সদর'],
            ['district_id' => '9','police_station_name' => 'Eidgaon','bn_police_station_name' => 'ঈদগাঁও'],
            ['district_id' => '39','police_station_name' => 'Madhyanagar','bn_police_station_name' => 'মধ্যনগর'],
            ['district_id' => '50','police_station_name' => 'Dasar','bn_police_station_name' => 'ডাসার'],

        ]);
    }
}
